### ISSUE TITLE
Current example (5.2.0, SB 3.2.0) not starting (StringIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by 5pielername** [joinfaces/joinfaces-maven-war-example#735]
Hi,

we are currently trying to update our JoinFaces apps to Spring Boot 3.2.0 and figured, that this example is not working. Throwing a similar exception as our own apps when starting from Terminal with `java -jar joinfaces-example-5.2.x.war`:

```
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
	at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:419) ~[tomcat-embed-core-10.1.16.jar!/:na]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:186) ~[tomcat-embed-core-10.1.16.jar!/:na]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332) ~[tomcat-embed-core-10.1.16.jar!/:na]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322) ~[tomcat-embed-core-10.1.16.jar!/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-10.1.16.jar!/:na]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145) ~[na:na]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866) ~[tomcat-embed-core-10.1.16.jar!/:na]
	... 36 common frames omitted
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -2, length 124
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606) ~[na:na]
	at java.base/java.lang.String.substring(String.java:2709) ~[na:na]
	at org.joinfaces.autoconfigure.tomcat.JsfTomcatLifecycleListener.base(JsfTomcatLifecycleListener.java:100) ~[joinfaces-autoconfigure-5.2.0.jar!/:5.2.0]
	at org.joinfaces.autoconfigure.tomcat.JsfTomcatLifecycleListener.addMainJarResourceSet(JsfTomcatLifecycleListener.java:196) ~[joinfaces-autoconfigure-5.2.0.jar!/:5.2.0]
	at org.joinfaces.autoconfigure.tomcat.JsfTomcatLifecycleListener.lifecycleEvent(JsfTomcatLifecycleListener.java:163) ~[joinfaces-autoconfigure-5.2.0.jar!/:5.2.0]
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:114) ~[tomcat-embed-core-10.1.16.jar!/:na]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4766) ~[tomcat-embed-core-10.1.16.jar!/:na]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) ~[tomcat-embed-core-10.1.16.jar!/:na]
	... 42 common frames omitted
```

I just tried with a new starter project with just JoinFaces as dependency, but get this exception too.

**Comment by persapiens** [comment]
Hi @5pielername ,

Please try joinfaces 5.2.1

**Comment by 5pielername** [comment]
Hi @persapiens ,

thanks for your reply and fixing this. Updating to 5.2.1 immediately fixed the startup issue!
